### ISSUE TITLE
Unable to run Java Quick Start against DAML-on-Fabric

### ISSUE THREAD

**Issue by radsal** [hacera/daml-on-fabric#26]
Encountered error while running the command on Step 3:

sbt "run --port 6865 --role provision,time,ledger,explorer ../quickstart/.daml/dist/quickstart-0.0.1.dar"

daml: 0.13.41
java: 1.8.0_201
scala: 2.12.11
sbt: 1.3.10
<img width="702" alt="daml_on_fabric" src="https://user-images.githubusercontent.com/6400446/83237550-b61fa800-a1b2-11ea-8c70-31712aaf241f.png">

**Comment by dasormeter** [comment]
@radsal this appears to be an sbt / java / scala compatibility issue likely based on the mix of versions you have similar to the problem detailed here : https://github.com/scala/bug/issues/11381

The project itself is using scala 2.12.8 and sbt 1.2.7
ThisBuild / scalaVersion := "2.12.8"

It certainly works in sbt 1.2.7 and 1.2.8

Can you try with Scala 2.12.8 instead?

As per Scala's recommendation 2.12.11 is recommended with JDK 11 rather than JDK 8
https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by dasormeter** [comment]
reminder on recommended combination from the readme
- **Java / JDK** version 1.8.0 (any reasonably up to date rev should work)
- **Scala** version 2.12.7 (2.12.8 also works)
- **SBT** version 1.2.8

**Comment by dasormeter** [comment]
I tried with a few different combinations -- it looks like the SBT version is the most likely culprit and Scala version should be okay.

So recommendation is that you stick with sbt 1.2.7 or 1.2.8

I also checked with JDK 11 / Scala 2.12.11 and that worked for me with SBT 1.2.8

SBT 1.3.10 looks to be problematic for sbt run on this project both with JDK8 and JDK11 regardless of Scala version.

https://www.scala-sbt.org/1.x/docs/sbt-1.3-Release-Notes.html

**Comment by radsal** [comment]
Using sbt version 1.2.8 works. Thanks.
